{
 "title": "dashboard_linux",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total {instance=\"localhost:9100\",device=\"sda\"}[10m])",
     "legendFormat": "кол-во операций ввода/вывода на жестком диске"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"localhost:9100\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\",mountpoint=\"/\"}",
     "legendFormat": "доступная память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"localhost:9100\",mountpoint=\"/\"}",
     "legendFormat": "занятая память"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/\"}",
     "legendFormat": "всего пямяти"
    }
   ]
  },
  {
   "title": "RAW free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}